### ISSUE TITLE
Dependency versions is out of sync between package.json and bower.json

### ISSUE THREAD

**Issue by gustavnikolaj** [gustavnikolaj/knockout-d3-line-graph#3]
I noticed this after merging #2 where the bower.json file was introduced. 

We need to check which version of knockout and d3 we rely on. Do we need anything from knockout 3.2 or can we go with knockout 3.1? Can we go lower than that? I'd like to find the lower boundary for which this still works, and then define the dependency as liberally as we can. Say 3.1 is the lowest knockout version that we can work with, then lets define the dependency as >= 3.1. The same goes for d3.

I'm a bit busy at the moment, so I would appreciate if you had time to look into this @sandermvanvliet.

**Comment by gustavnikolaj** [comment]
I've added you as a collaborator now @sandermvanvliet :-) If you don't have time this is not that important, and I will eventually get around to it my self...

**Comment by sandermvanvliet** [comment]
I'll see if I can figure this out relatively easily, I think it'll depend a bit upon what requirements there are outside of just binding the data.

**Comment by gustavnikolaj** [comment]
Synced them up and required knockout 3.4.2 all over the place.
